# Copyright (C) Microarray
# MicroArray Fprint Driver Code
# MAKEFILE
# Date: 2017-3-15
# Version: v4.0.06 
# Author: guq
# Contact: guq@microarray.com.cn



obj-$(CONFIG_MICROARRAY_FINGERPRINT) += qcom-settings.o
obj-$(CONFIG_MICROARRAY_FINGERPRINT) += madev.o



